version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: cimg/dotnet:8.0.1-node  # includes both .NET 8 SDK and Node.js

jobs:
  build-and-scan:
    executor: dotnet-executor
    steps:
      - checkout

      - run:
          name: Install SonarScanner CLI
          command: |
            dotnet tool install --global dotnet-sonarscanner
            echo 'export PATH="$PATH:/root/.dotnet/tools"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Restore NuGet Packages
          command: dotnet restore AMLCustomerPaymentsPortal.sln

      - run:
          name: SonarCloud Begin Analysis
          command: |
            dotnet-sonarscanner begin \
              /k:"manyanocwane_AMLCustomerPaymentsPortal" \
              /o:"manyanocwane" \
              /d:sonar.login=$SONAR_TOKEN \
              /d:sonar.host.url="https://sonarcloud.io" \
              /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      - run:
          name: Build Project
          command: dotnet build AMLCustomerPaymentsPortal.sln --no-restore

      - run:
          name: End SonarCloud Analysis
          command: |
            dotnet-sonarscanner end /d:sonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build-and-analyze:
    jobs:
      - build-and-scan
